[source]
driver = "postgres"
host = "postgres"
port = 5432
dbname = "diffly"
user = "diffly"
password = "diffly"
schema = "source"

[target]
driver = "postgres"
host = "postgres"
port = 5432
dbname = "diffly"
user = "diffly"
password = "diffly"
schema = "target"

[diff]
[[diff.tables]]
name = "pricing_rules"
primary_key = ["id"]
excluded_columns = ["created_at", "updated_at"]

[[diff.tables]]
name = "discount_tiers"
primary_key = ["id"]

[[diff.tables]]
name = "shipping_rules"
primary_key = ["id"]

[[diff.tables]]
name = "tax_rules"
primary_key = ["region_code", "product_category"]

[[diff.tables]]
name = "no_change_rules"
primary_key = ["id"]

[[diff.tables]]
name = "nullable_rules"
primary_key = ["id"]

[[diff.tables]]
name = "jsonb_rules"
primary_key = ["id"]

[[diff.tables]]
name = "empty_target_rules"
primary_key = ["id"]

[[diff.tables]]
name = "empty_source_rules"
primary_key = ["id"]

[[diff.tables]]
name = "quoted_rules"
primary_key = ["id"]

[output]
dir = "./output"
