name: Tests and release

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "diffly-*"
  pull_request:

env:
  CRATE_NAME: diffly
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: 1

jobs:
  test:
    name: ${{ matrix.platform.os-name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.runs-on }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os-name: FreeBSD-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-freebsd
            bin: ${{ env.CRATE_NAME }
            name: ${{ env.CRATE_NAME }-FreeBSD-x86_64.tar.gz
            skip-tests: true
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl
            bin: ${{ env.CRATE_NAME }
            name: ${{ env.CRATE_NAME }-Linux-x86_64-musl.tar.gz
          - os-name: Linux-aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl
            bin: ${{ env.CRATE_NAME }
            name: ${{ env.CRATE_NAME }-Linux-aarch64-musl.tar.gz
          - os-name: Linux-arm
            runs-on: ubuntu-24.04
            target: arm-unknown-linux-musleabi
            bin: ${{ env.CRATE_NAME }
            name: ${{ env.CRATE_NAME }-Linux-arm-musl.tar.gz
          - os-name: Linux-i686
            runs-on: ubuntu-24.04
            target: i686-unknown-linux-musl
            bin: ${{ env.CRATE_NAME }
            name: ${{ env.CRATE_NAME }-Linux-i686-musl.tar.gz
            skip-tests: true
          - os-name: Linux-powerpc
            runs-on: ubuntu-24.04
            target: powerpc-unknown-linux-gnu
            bin: ${{ env.CRATE_NAME }
            name: ${{ env.CRATE_NAME }-Linux-powerpc-gnu.tar.gz
            skip-tests: true
          - os-name: Linux-powerpc64
            runs-on: ubuntu-24.04
            target: powerpc64-unknown-linux-gnu
            bin: ${{ env.CRATE_NAME }
            name: ${{ env.CRATE_NAME }-Linux-powerpc64-gnu.tar.gz
            skip-tests: true
          - os-name: Linux-powerpc64le
            runs-on: ubuntu-24.04
            target: powerpc64le-unknown-linux-gnu
            bin: ${{ env.CRATE_NAME }
            name: ${{ env.CRATE_NAME }-Linux-powerpc64le.tar.gz
            skip-tests: true
          - os-name: Linux-riscv64
            runs-on: ubuntu-24.04
            target: riscv64gc-unknown-linux-gnu
            bin: ${{ env.CRATE_NAME }
            name: ${{ env.CRATE_NAME }-Linux-riscv64gc-gnu.tar.gz
          - os-name: Linux-s390x
            runs-on: ubuntu-24.04
            target: s390x-unknown-linux-gnu
            bin: ${{ env.CRATE_NAME }
            name: ${{ env.CRATE_NAME }-Linux-s390x-gnu.tar.gz
            skip-tests: true
          - os-name: NetBSD-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-netbsd
            bin: ${{ env.CRATE_NAME }
            name: ${{ env.CRATE_NAME }-NetBSD-x86_64.tar.gz
            skip-tests: true
          - os-name: Windows-aarch64
            runs-on: windows-latest
            target: aarch64-pc-windows-msvc
            bin: ${{ env.CRATE_NAME }.exe
            name: ${{ env.CRATE_NAME }-Windows-aarch64.zip
            skip-tests: true
          - os-name: Windows-i686
            runs-on: windows-latest
            target: i686-pc-windows-msvc
            bin: ${{ env.CRATE_NAME }.exe
            name: ${{ env.CRATE_NAME }-Windows-i686.zip
            skip-tests: true
          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            bin: ${{ env.CRATE_NAME }.exe
            name: ${{ env.CRATE_NAME }-Windows-x86_64.zip
          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
            bin: ${{ env.CRATE_NAME }
            name: ${{ env.CRATE_NAME }-Darwin-x86_64.tar.gz
          - os-name: macOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin
            bin: ${{ env.CRATE_NAME }
            name: ${{ env.CRATE_NAME }-Darwin-aarch64.tar.gz
        toolchain:
          - stable
        include:
          - platform:
              os-name: Linux-x86_64
              runs-on: ubuntu-24.04
              target: x86_64-unknown-linux-musl
              bin: ${{ env.CRATE_NAME }
            toolchain: beta
          - platform:
              os-name: Linux-x86_64
              runs-on: ubuntu-24.04
              target: x86_64-unknown-linux-musl
              bin: ${{ env.CRATE_NAME }
            toolchain: nightly
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Run tests
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: "test"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release --features cli"
          # This works around the issue in https://github.com/cross-rs/cross/issues/1450. The `main`
          # branch updated its images long ago, but the last cross release, 0.2.5, is still using
          # Ubuntu 16.04 as the base for some images.
          #
          # This also contains a fix for https://github.com/cross-rs/cross/issues/1619. Previously,
          # we used an earlier commit, but this started erroring because some dependencies included
          # cross config.
          cross-version: 107433fa9d71d7eb506cd5bf5467bab89edb7a52
        if: ${{ !matrix.platform.skip-tests }}
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release --features cli"
          strip: true
          cross-version: 107433fa9d71d7eb506cd5bf5467bab89edb7a52
      - name: Update CHANGELOG
        id: changelog
        if: startsWith(github.ref, 'refs/tags/')
        uses: requarks/changelog-action@v1
        with:
          token: ${{ env.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v1
        with:
          executable-name: ${{ env.CRATE_NAME }}
          target: ${{ matrix.platform.target }}
          changes-file: CHANGELOG.md
        if: matrix.toolchain == 'stable'
